{
 "title": "KPI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 1, "y": 0 },
   "options": {
    "content": "<p style=\"font-size: 24px; font-weight: 600; margin-bottom: 0;\">\n  Accounts & Smart Contracts\n</p>\n<p>\n  Active accounts and smart contracts over the last 90 days\n</p>"
   }
  },
  {
   "title": "Active Accounts",
   "type": "canvas",
   "description": "See explainer below.",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select * from ecosystem.hashgraph_dashboard;"
    }
   ]
  },
  {
   "title": "Change (7 Days)",
   "type": "canvas",
   "description": "The most recent 7 day period compared to the previous 7 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (30 Days)",
   "type": "canvas",
   "description": "The most recent 30 day period compared to the previous 30 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (90 Days)",
   "type": "canvas",
   "description": "The most recent 90 day period compared to the previous 90 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (1 Year)",
   "type": "canvas",
   "description": "The most recent 365 day period compared to the previous 365 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Active Accounts Explained",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 12 },
   "options": {
    "content": "An active account is any account that originates at least one transaction during a given timeframe. Unlike accounts that only receive value or tokens, active accounts must initiate an operation—such as sending a payment or interacting with a service—thus demonstrating direct network engagement. This includes smart contracts.\n\n<a href=\"https://docs.hgraph.com/hedera-stats/active-accounts\" target=\"_blank\">View methodology & documentation →</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 1, "y": 17 } },
  {
   "title": "Developer Accounts",
   "type": "canvas",
   "description": "See explainer below.",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (7 Days)",
   "type": "canvas",
   "description": "The most recent 7 day period compared to the previous 7 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (30 Days)",
   "type": "canvas",
   "description": "The most recent 30 day period compared to the previous 30 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (90 Days)",
   "type": "canvas",
   "description": "The most recent 90 day period compared to the previous 90 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (1 Year)",
   "type": "canvas",
   "description": "The most recent 365 day period compared to the previous 365 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Developer Accounts Explained",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 1, "y": 27 },
   "options": {
    "content": "A developer account is any account that performs at least one “creative” or infrastructure-oriented action over a specified period. Examples include deploying or updating smart contracts, creating or minting tokens, or setting up and modifying consensus topics. These accounts represent users who are actively building or expanding the network’s capabilities rather than simply consuming existing services.\n\n<a href=\"https://docs.hgraph.com/hedera-stats/developer-accounts\" target=\"_blank\">View methodology & documentation →</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 1, "y": 33 } },
  {
   "title": "Retail Accounts",
   "type": "canvas",
   "description": "See explainer below.",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (7 Days)",
   "type": "canvas",
   "description": "The most recent 7 day period compared to the previous 7 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (30 Days)",
   "type": "canvas",
   "description": "The most recent 30 day period compared to the previous 30 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (90 Days)",
   "type": "canvas",
   "description": "The most recent 90 day period compared to the previous 90 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (1 Year)",
   "type": "canvas",
   "description": "The most recent 365 day period compared to the previous 365 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Retail Accounts Explained",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 43 },
   "options": {
    "content": "A \"retail account\" is essentially an active account that is neither a developer account nor a smart contract account. This category is determined after identifying active and developer accounts, as well as distinguishing active smart contracts.\n\n<a href=\"https://docs.hgraph.com/hedera-stats/retail-accounts\" target=\"_blank\">View methodology & documentation →</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 1, "y": 48 } },
  {
   "title": "Active Smart Contracts",
   "type": "canvas",
   "description": "See explainer below.",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (7 Days)",
   "type": "canvas",
   "description": "The most recent 7 day period compared to the previous 7 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (30 Days)",
   "type": "canvas",
   "description": "The most recent 30 day period compared to the previous 30 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (90 Days)",
   "type": "canvas",
   "description": "The most recent 90 day period compared to the previous 90 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (1 Year)",
   "type": "canvas",
   "description": "The most recent 365 day period compared to the previous 365 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Active Contracts Explained",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 58 },
   "options": {
    "content": "The number of unique smart contracts that have been invoked through at least one state-changing (gas-consuming) transaction within a specified time window. This statistic highlights how many contracts are actively in use, rather than just deployed and idle, providing a snapshot of real engagement and activity in the ecosystem.\n\n<a href=\"https://docs.hgraph.com/hedera-stats/active-contracts\" target=\"_blank\">View methodology & documentation →</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 1, "y": 63 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 1, "y": 65 },
   "options": {
    "content": "<p style=\"font-size: 24px; font-weight: 600; margin-bottom: 0;\">\n  TVL & Stablecoin Market Cap\n</p>\n<p>\n Current day totals for value locked and stablecoin market cap (including recent change).\n</p>"
   }
  },
  {
   "title": "Total Value Locked (TVL)",
   "type": "canvas",
   "description": "See explainer below.",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select total from ecosystem.metric where name = 'network_tvl' and period = 'day' order by timestamp_range desc limit 1;"
    }
   ]
  },
  {
   "title": "Change (7 Days)",
   "type": "canvas",
   "description": "The most recent 7 day period compared to the previous 7 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH previous AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'network_tvl'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    OFFSET 7 LIMIT 1\n), \ncurrent AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'network_tvl'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    LIMIT 1\n)\nSELECT \n    (current.total::decimal / previous.total - 1) * 100 AS change\nFROM current, previous;"
    }
   ]
  },
  {
   "title": "Change (30 Days)",
   "type": "canvas",
   "description": "The most recent 30 day period compared to the previous 30 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH previous AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'network_tvl'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    OFFSET 30 LIMIT 1\n), \ncurrent AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'network_tvl'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    LIMIT 1\n)\nSELECT \n    (current.total::decimal / previous.total - 1) * 100 AS change\nFROM current, previous;"
    }
   ]
  },
  {
   "title": "Change (90 Days)",
   "type": "canvas",
   "description": "The most recent 90 day period compared to the previous 90 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH previous AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'network_tvl'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    OFFSET 90 LIMIT 1\n), \ncurrent AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'network_tvl'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    LIMIT 1\n)\nSELECT \n    (current.total::decimal / previous.total - 1) * 100 AS change\nFROM current, previous;"
    }
   ]
  },
  {
   "title": "Change (1 Year)",
   "type": "canvas",
   "description": "The most recent 365 day period compared to the previous 365 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH previous AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'network_tvl'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    OFFSET 365 LIMIT 1\n), \ncurrent AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'network_tvl'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    LIMIT 1\n)\nSELECT \n    (current.total::decimal / previous.total - 1) * 100 AS change\nFROM current, previous;"
    }
   ]
  },
  {
   "title": "Total Value Locked (TVL) Explained",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 77 },
   "options": {
    "content": "Total Value Locked (TVL) represents the total amount of assets locked within decentralized finance (DeFi) protocols on the Hedera network. This metric provides insights into liquidity, ecosystem adoption, and capital efficiency within Hedera’s DeFi landscape. This leverages data from 3rd party data sources like DeFi Llama.\n\n<a href=\"https://docs.hgraph.com/hedera-stats/total-value-locked\" target=\"_blank\">View methodology & documentation →</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 1, "y": 82 } },
  {
   "title": "Stablecoin Market Cap",
   "type": "canvas",
   "description": "See explainer below.",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select total from ecosystem.metric where name = 'stablecoin_marketcap' and period = 'day' order by timestamp_range desc limit 1;"
    }
   ]
  },
  {
   "title": "Change (7 Days)",
   "type": "canvas",
   "description": "The most recent 7 day period compared to the previous 7 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH previous AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'stablecoin_marketcap'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    OFFSET 7 LIMIT 1\n), \ncurrent AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'stablecoin_marketcap'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    LIMIT 1\n)\nSELECT \n    (current.total::decimal / previous.total - 1) * 100 AS change\nFROM current, previous;"
    }
   ]
  },
  {
   "title": "Change (30 Days)",
   "type": "canvas",
   "description": "The most recent 30 day period compared to the previous 30 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH previous AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'stablecoin_marketcap'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    OFFSET 30 LIMIT 1\n), \ncurrent AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'stablecoin_marketcap'\n    AND period = 'day'\n    ORDER BY timestamp_range DESC \n    LIMIT 1\n)\nSELECT \n    (current.total::decimal / previous.total - 1) * 100 AS change\nFROM current, previous;"
    }
   ]
  },
  {
   "title": "Change 90 Days",
   "type": "canvas",
   "description": "The most recent 90 day period compared to the previous 90 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH previous AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'stablecoin_marketcap' \n    ORDER BY timestamp_range DESC \n    OFFSET 90 LIMIT 1\n), \ncurrent AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'stablecoin_marketcap' \n    ORDER BY timestamp_range DESC \n    LIMIT 1\n)\nSELECT \n    (current.total::decimal / previous.total - 1) * 100 AS change\nFROM current, previous;"
    }
   ]
  },
  {
   "title": "Change (1 year)",
   "type": "canvas",
   "description": "The most recent 365 day period compared to the previous 365 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH previous AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'stablecoin_marketcap' \n    ORDER BY timestamp_range DESC \n    OFFSET 365 LIMIT 1\n), \ncurrent AS (\n    SELECT total \n    FROM ecosystem.metric \n    WHERE name = 'stablecoin_marketcap' \n    ORDER BY timestamp_range DESC \n    LIMIT 1\n)\nSELECT \n    (current.total::decimal / previous.total - 1) * 100 AS change\nFROM current, previous;"
    }
   ]
  },
  {
   "title": "Stablecoin Market Cap Explained",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 92 },
   "options": {
    "content": "The Stablecoin Market Cap statistic tracks the total market capitalization of stablecoins circulating on the Hedera network. This statistic provides insight into the adoption and liquidity of stablecoins within the ecosystem.\n\n<a href=\"https://docs.hgraph.com/hedera-stats/stablecoin-market-cap\" target=\"_blank\">View methodology & documentation →</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 1, "y": 97 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 1, "y": 99 },
   "options": {
    "content": "<p style=\"font-size: 24px; font-weight: 600; margin-bottom: 0;\">\n  Revenue\n</p>\n<p>\n  Total transaction fees collected in the last 90 days.\n"
   }
  },
  {
   "title": "Revenue",
   "type": "canvas",
   "description": "See explainer below.",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (7 days)",
   "type": "canvas",
   "description": "The most recent 7 day period compared to the previous 7 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (30 Days)",
   "type": "canvas",
   "description": "The most recent 30 day period compared to the previous 30 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (90 Days)",
   "type": "canvas",
   "description": "The most recent 30 day period compared to the previous 30 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Change (1 Year)",
   "type": "canvas",
   "description": "The most recent 365 day period compared to the previous 365 day period.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Revenue Explained",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 1, "y": 111 },
   "options": {
    "content": "Hedera’s revenue is the sum of all transaction fees across the mainnet. Each transaction pays fees to the consensus nodes, the staking account, the node rewards account, and the Hedera treasury. By examining each transaction and tracking these fee allocations, Hedera calculates its total network revenue and breaks it down by service type (HTS, HSCS, HCS, and Other).\n\n<a href=\"https://docs.hgraph.com/hedera-stats/revenue\" target=\"_blank\">View methodology & documentation →</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 1, "y": 116 } }
 ]
}