export type MetricType = 'sql' | 'api';

export interface MetricDef {
  name: string;
  type: MetricType;
}

export interface JobDef {
  name: string;
  cron: string;
  period: string;
  truncation: string;
  metrics: MetricDef[];
  retention?: { metricName: string; hours: number };
}

export const API_METRICS = new Set([
  'avg_usd_conversion',
  'network_tvl',
  'stablecoin_marketcap',
]);

function m(names: string[]): MetricDef[] {
  return names.map((name) => ({
    name,
    type: (API_METRICS.has(name) ? 'api' : 'sql') as MetricType,
  }));
}

// Mirrors the schedules from src/jobs/pg_cron_metrics.sql
export const jobs: JobDef[] = [
  {
    name: 'minute',
    cron: '* * * * *',
    period: 'minute',
    truncation: 'minute',
    metrics: m(['avg_usd_conversion']),
    retention: { metricName: 'avg_usd_conversion', hours: 72 },
  },
  {
    name: 'hour',
    cron: '1 * * * *',
    period: 'hour',
    truncation: 'hour',
    metrics: m([
      'avg_usd_conversion',
      'hbar_total_released',
      'hbar_market_cap',
      'active_developer_accounts',
      'active_retail_accounts',
      'active_smart_contracts',
      'avg_gas_used',
      'avg_gas_used_contract_call',
      'avg_gas_used_ethereum_tx',
      'avg_gas_used_contract_create',
      'active_accounts',
      'active_ecdsa_accounts',
      'active_ed25519_accounts',
      'network_fee',
      'avg_network_fee',
      'network_tps',
      'new_accounts',
      'new_ecdsa_accounts',
      'new_ecdsa_accounts_real_evm',
      'new_ed25519_accounts',
      'new_smart_contracts',
      'new_transactions',
      'new_hcs_transactions',
      'new_hfs_transactions',
      'new_hscs_transactions',
      'new_hts_transactions',
      'new_crypto_transactions',
      'new_other_transactions',
      'nft_collections_created',
    ]),
  },
  {
    name: 'day',
    cron: '2 0 * * *',
    period: 'day',
    truncation: 'day',
    metrics: m([
      'total_accounts',
      'total_ecdsa_accounts',
      'total_ed25519_accounts',
      'total_smart_contracts',
      'total_erc1155_accounts',
      'total_erc1400_accounts',
      'hbar_total_released',
      'avg_usd_conversion',
      'hbar_market_cap',
      'active_developer_accounts',
      'active_retail_accounts',
      'active_smart_contracts',
      'avg_gas_used',
      'avg_gas_used_contract_call',
      'avg_gas_used_ethereum_tx',
      'avg_gas_used_contract_create',
      'active_accounts',
      'active_ecdsa_accounts',
      'active_ed25519_accounts',
      'network_fee',
      'avg_network_fee',
      'network_tps',
      'new_accounts',
      'new_ecdsa_accounts',
      'new_ecdsa_accounts_real_evm',
      'new_ed25519_accounts',
      'new_smart_contracts',
      'new_transactions',
      'new_hcs_transactions',
      'new_hfs_transactions',
      'new_hscs_transactions',
      'new_hts_transactions',
      'new_crypto_transactions',
      'new_other_transactions',
      'nft_collections_created',
      'total_transactions',
      'total_hcs_transactions',
      'total_crypto_transactions',
      'total_hfs_transactions',
      'total_hscs_transactions',
      'total_hts_transactions',
      'total_other_transactions',
    ]),
  },
  {
    name: 'day_api',
    cron: '5 0 * * *',
    period: 'day',
    truncation: 'day',
    metrics: m(['network_tvl', 'stablecoin_marketcap']),
  },
  {
    name: 'week',
    cron: '2 0 * * 0',
    period: 'week',
    truncation: 'week',
    metrics: m([
      'total_accounts',
      'total_ecdsa_accounts',
      'total_ed25519_accounts',
      'total_smart_contracts',
      'total_erc1155_accounts',
      'hbar_total_released',
      'hbar_market_cap',
      'active_developer_accounts',
      'active_retail_accounts',
      'active_smart_contracts',
      'avg_gas_used',
      'avg_gas_used_contract_call',
      'avg_gas_used_ethereum_tx',
      'avg_gas_used_contract_create',
      'active_accounts',
      'active_ecdsa_accounts',
      'active_ed25519_accounts',
      'new_ecdsa_accounts_real_evm',
      'new_transactions',
      'new_hcs_transactions',
      'new_hfs_transactions',
      'new_hscs_transactions',
      'new_hts_transactions',
      'new_crypto_transactions',
      'new_other_transactions',
      'total_transactions',
      'total_hcs_transactions',
      'total_crypto_transactions',
      'total_hfs_transactions',
      'total_hscs_transactions',
      'total_hts_transactions',
      'total_other_transactions',
      'network_tps',
    ]),
  },
  {
    name: 'month',
    cron: '4 0 1 * *',
    period: 'month',
    truncation: 'month',
    metrics: m([
      'total_accounts',
      'total_ecdsa_accounts',
      'total_ed25519_accounts',
      'total_smart_contracts',
      'total_erc1155_accounts',
      'hbar_total_released',
      'hbar_market_cap',
      'active_developer_accounts',
      'active_retail_accounts',
      'active_smart_contracts',
      'avg_gas_used',
      'avg_gas_used_contract_call',
      'avg_gas_used_ethereum_tx',
      'avg_gas_used_contract_create',
      'active_accounts',
      'active_ecdsa_accounts',
      'active_ed25519_accounts',
      'new_ecdsa_accounts_real_evm',
      'new_transactions',
      'new_hcs_transactions',
      'new_hfs_transactions',
      'new_hscs_transactions',
      'new_hts_transactions',
      'new_crypto_transactions',
      'new_other_transactions',
      'total_transactions',
      'total_hcs_transactions',
      'total_crypto_transactions',
      'total_hfs_transactions',
      'total_hscs_transactions',
      'total_hts_transactions',
      'total_other_transactions',
      'network_tps',
    ]),
  },
  {
    name: 'quarter',
    cron: '8 0 1 1,4,7,10 *',
    period: 'quarter',
    truncation: 'quarter',
    metrics: m([
      'total_accounts',
      'total_ecdsa_accounts',
      'total_ed25519_accounts',
      'total_smart_contracts',
      'hbar_total_released',
      'hbar_market_cap',
      'active_developer_accounts',
      'active_retail_accounts',
      'active_smart_contracts',
      'avg_gas_used',
      'avg_gas_used_contract_call',
      'avg_gas_used_ethereum_tx',
      'avg_gas_used_contract_create',
      'active_accounts',
      'active_ecdsa_accounts',
      'active_ed25519_accounts',
      'new_ecdsa_accounts_real_evm',
      'new_transactions',
      'new_hcs_transactions',
      'new_hfs_transactions',
      'new_hscs_transactions',
      'new_hts_transactions',
      'new_crypto_transactions',
      'new_other_transactions',
      'total_transactions',
      'total_hcs_transactions',
      'total_crypto_transactions',
      'total_hfs_transactions',
      'total_hscs_transactions',
      'total_hts_transactions',
      'total_other_transactions',
      'network_tps',
    ]),
  },
  {
    name: 'year',
    cron: '14 0 1 1 *',
    period: 'year',
    truncation: 'year',
    metrics: m([
      'total_accounts',
      'total_ecdsa_accounts',
      'total_ed25519_accounts',
      'total_smart_contracts',
      'hbar_total_released',
      'hbar_market_cap',
      'active_developer_accounts',
      'active_retail_accounts',
      'active_smart_contracts',
      'avg_gas_used',
      'avg_gas_used_contract_call',
      'avg_gas_used_ethereum_tx',
      'avg_gas_used_contract_create',
      'active_accounts',
      'active_ecdsa_accounts',
      'active_ed25519_accounts',
      'new_ecdsa_accounts_real_evm',
      'new_transactions',
      'new_hcs_transactions',
      'new_hfs_transactions',
      'new_hscs_transactions',
      'new_hts_transactions',
      'new_crypto_transactions',
      'new_other_transactions',
      'total_transactions',
      'total_hcs_transactions',
      'total_crypto_transactions',
      'total_hfs_transactions',
      'total_hscs_transactions',
      'total_hts_transactions',
      'total_other_transactions',
      'network_tps',
    ]),
  },
];

// All known SQL metric function names (for validation)
export const KNOWN_SQL_METRICS = new Set(
  jobs
    .flatMap((j) => j.metrics)
    .filter((m) => m.type === 'sql')
    .map((m) => m.name),
);
